# Generated by Django 6.0.5 on 2026-06-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tet',
            new_name='text',
        ),
    ]
